# Generated by Django 4.2 on 2023-04-12 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Access',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('EDRPOU', models.IntegerField(verbose_name='ЕДРПОУ')),
                ('FullName', models.CharField(max_length=255, verbose_name='Полное название')),
                ('Name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Краткое название')),
                ('Oblast', models.CharField(blank=True, max_length=255, null=True, verbose_name='Область')),
                ('Localithation', models.CharField(blank=True, choices=[('Облако', 'Облако'), ('Локально', 'Локально')], max_length=8, null=True, verbose_name='Локализация')),
                ('Level_medical_help', models.CharField(blank=True, choices=[('Первичка', 'Первичка'), ('Вторичка', 'Вторичка'), ('Третичка', 'Третичка')], max_length=8, null=True, verbose_name='Уровень мед. помощи')),
                ('License', models.IntegerField(blank=True, null=True, verbose_name='Количество лицензий')),
                ('Contact', models.TextField(blank=True, null=True, verbose_name='Контакты')),
                ('RDP_SQL_IP', models.CharField(blank=True, max_length=50, null=True, verbose_name='RDP SQL IP')),
                ('RDP_SQL_Login', models.CharField(blank=True, max_length=50, null=True, verbose_name='RDP SQL Login')),
                ('RDP_SQL_Password', models.CharField(blank=True, max_length=50, null=True, verbose_name='RDP SQL Password')),
                ('SQL_Server_Password', models.CharField(blank=True, max_length=50, null=True, verbose_name='SQL Server Password')),
                ('RDP_APP_IP', models.CharField(blank=True, max_length=50, null=True, verbose_name='RDP APP IP')),
                ('RDP_APP_Login', models.CharField(blank=True, max_length=50, null=True, verbose_name='RDP APP Login')),
                ('RDP_APP_Password', models.CharField(blank=True, max_length=50, null=True, verbose_name='RDP APP Password')),
                ('EMCI_IP', models.CharField(blank=True, max_length=50, null=True, verbose_name='EMCI IP')),
                ('EMCI_Port', models.CharField(blank=True, max_length=50, null=True, verbose_name='EMCI Port')),
                ('EMCI_Login', models.CharField(blank=True, max_length=50, null=True, verbose_name='EMCI Login')),
                ('EMCI_Password', models.CharField(blank=True, max_length=50, null=True, verbose_name='EMCI Password')),
                ('Info', models.TextField(blank=True, null=True, verbose_name='Info')),
            ],
        ),
    ]
